name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag latex:$(date +%s)
    - name: Run the PDF build inside container
      run: docker run --rm -i -v "$PWD":/data latex pdflatex oc_resume.tex 
